
database:
  host: *****
  user: root
  password: *****
  database: gdetus

server:
  port: 8080

https:
  port: 443
  keys:
    private: key.pem
    public: certificate.pem
    root: req.ru.crt.pem

nodemailer:
  service: Gmail
  auth: 
    user: *****@gmail.com
    pass: *****
